### ISSUE TITLE
Can i add a good  background in the front page

### ISSUE THREAD

**Issue by irfan-iiitr** [mahesh-barapatre/ChatRoom#3]

**Comment by mahesh-barapatre** [comment]
if you want to complete hacktoberfest there are 2 more repo in my profile.
open a issue there and i will label that as hacktober accepted
and will merge immediately

**Comment by mahesh-barapatre** [comment]
for this issue you are assigned for the same...change the background that suits the theme of the front page....if you have not registered for hacktoberfest 23, register there first ....
